const input = `L.LL.LL.LL
LLLLLLL.LL
L.L.L..L..
LLLL.LL.LL
L.LL.LL.LL
L.LLLLL.LL
..L.L.....
LLLLLLLLLL
L.LLLLLL.L
L.LLLLL.LL`;

const part1Changes = [
    [
        "L.LL.LL.LL".split(""),
        "LLLLLLL.LL".split(""),
        "L.L.L..L..".split(""),
        "LLLL.LL.LL".split(""),
        "L.LL.LL.LL".split(""),
        "L.LLLLL.LL".split(""),
        "..L.L.....".split(""),
        "LLLLLLLLLL".split(""),
        "L.LLLLLL.L".split(""),
        "L.LLLLL.LL".split(""),
    ],
    [
        "#.##.##.##".split(""),
        "#######.##".split(""),
        "#.#.#..#..".split(""),
        "####.##.##".split(""),
        "#.##.##.##".split(""),
        "#.#####.##".split(""),
        "..#.#.....".split(""),
        "##########".split(""),
        "#.######.#".split(""),
        "#.#####.##".split(""),
    ],
    [
        "#.LL.L#.##".split(""),
        "#LLLLLL.L#".split(""),
        "L.L.L..L..".split(""),
        "#LLL.LL.L#".split(""),
        "#.LL.LL.LL".split(""),
        "#.LLLL#.##".split(""),
        "..L.L.....".split(""),
        "#LLLLLLLL#".split(""),
        "#.LLLLLL.L".split(""),
        "#.#LLLL.##".split(""),
    ],
    [
        "#.##.L#.##".split(""),
        "#L###LL.L#".split(""),
        "L.#.#..#..".split(""),
        "#L##.##.L#".split(""),
        "#.##.LL.LL".split(""),
        "#.###L#.##".split(""),
        "..#.#.....".split(""),
        "#L######L#".split(""),
        "#.LL###L.L".split(""),
        "#.#L###.##".split(""),
    ],
    [
        "#.#L.L#.##".split(""),
        "#LLL#LL.L#".split(""),
        "L.L.L..#..".split(""),
        "#LLL.##.L#".split(""),
        "#.LL.LL.LL".split(""),
        "#.LL#L#.##".split(""),
        "..L.L.....".split(""),
        "#L#LLLL#L#".split(""),
        "#.LLLLLL.L".split(""),
        "#.#L#L#.##".split(""),
    ],
    [
        "#.#L.L#.##".split(""),
        "#LLL#LL.L#".split(""),
        "L.#.L..#..".split(""),
        "#L##.##.L#".split(""),
        "#.#L.LL.LL".split(""),
        "#.#L#L#.##".split(""),
        "..L.L.....".split(""),
        "#L#L##L#L#".split(""),
        "#.LLLLLL.L".split(""),
        "#.#L#L#.##".split(""),
    ],
];

const part2Changes = [
    [
        "L.LL.LL.LL".split(""),
        "LLLLLLL.LL".split(""),
        "L.L.L..L..".split(""),
        "LLLL.LL.LL".split(""),
        "L.LL.LL.LL".split(""),
        "L.LLLLL.LL".split(""),
        "..L.L.....".split(""),
        "LLLLLLLLLL".split(""),
        "L.LLLLLL.L".split(""),
        "L.LLLLL.LL".split(""),
    ],
    [
        "#.##.##.##".split(""),
        "#######.##".split(""),
        "#.#.#..#..".split(""),
        "####.##.##".split(""),
        "#.##.##.##".split(""),
        "#.#####.##".split(""),
        "..#.#.....".split(""),
        "##########".split(""),
        "#.######.#".split(""),
        "#.#####.##".split(""),
    ],
    [
        "#.LL.LL.L#".split(""),
        "#LLLLLL.LL".split(""),
        "L.L.L..L..".split(""),
        "LLLL.LL.LL".split(""),
        "L.LL.LL.LL".split(""),
        "L.LLLLL.LL".split(""),
        "..L.L.....".split(""),
        "LLLLLLLLL#".split(""),
        "#.LLLLLL.L".split(""),
        "#.LLLLL.L#".split(""),
    ],
    [
        "#.L#.##.L#".split(""),
        "#L#####.LL".split(""),
        "L.#.#..#..".split(""),
        "##L#.##.##".split(""),
        "#.##.#L.##".split(""),
        "#.#####.#L".split(""),
        "..#.#.....".split(""),
        "LLL####LL#".split(""),
        "#.L#####.L".split(""),
        "#.L####.L#".split(""),
    ],
    [
        "#.L#.L#.L#".split(""),
        "#LLLLLL.LL".split(""),
        "L.L.L..#..".split(""),
        "##LL.LL.L#".split(""),
        "L.LL.LL.L#".split(""),
        "#.LLLLL.LL".split(""),
        "..L.L.....".split(""),
        "LLLLLLLLL#".split(""),
        "#.LLLLL#.L".split(""),
        "#.L#LL#.L#".split(""),
    ],
    [
        "#.L#.L#.L#".split(""),
        "#LLLLLL.LL".split(""),
        "L.L.L..#..".split(""),
        "##L#.#L.L#".split(""),
        "L.L#.#L.L#".split(""),
        "#.L####.LL".split(""),
        "..#.#.....".split(""),
        "LLL###LLL#".split(""),
        "#.LLLLL#.L".split(""),
        "#.L#LL#.L#".split(""),
    ],
    [
        "#.L#.L#.L#".split(""),
        "#LLLLLL.LL".split(""),
        "L.L.L..#..".split(""),
        "##L#.#L.L#".split(""),
        "L.L#.LL.L#".split(""),
        "#.LLLL#.LL".split(""),
        "..#.L.....".split(""),
        "LLL###LLL#".split(""),
        "#.LLLLL#.L".split(""),
        "#.L#LL#.L#".split(""),
    ],
];

const occupiedSeats = [
    {
        arrangement: [
            ".......#.".split(""),
            "...#.....".split(""),
            ".#.......".split(""),
            ".........".split(""),
            "..#L....#".split(""),
            "....#....".split(""),
            ".........".split(""),
            "#........".split(""),
            "...#.....".split(""),
        ],
        testCoordinates: [4, 3],
        adjacentlyOccupied: 2,
        visiblyOccupied: 8,
    },
    {
        arrangement: [
            ".............".split(""),
            ".L.L.#.#.#.#.".split(""),
            ".............".split(""),
        ],
        testCoordinates: [1, 1],
        adjacentlyOccupied: 0,
        visiblyOccupied: 0,
    },
    {
        arrangement: [
            ".##.##.".split(""),
            "#.#.#.#".split(""),
            "##...##".split(""),
            "...L...".split(""),
            "##...##".split(""),
            "#.#.#.#".split(""),
            ".##.##.".split(""),
        ],
        testCoordinates: [3, 3],
        adjacentlyOccupied: 0,
        visiblyOccupied: 0,
    },
];

export { input, part1Changes, part2Changes, occupiedSeats };
